version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: chat-theme-picker-dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    tty: true
    stdin_open: true 